name: Convert Ruleset
on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *'  # 每天 北京时间 11:00

jobs:
  run_convert:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Download mihomo
        run: |
          curl -L -o mihomo.gz https://github.com/MetaCubeX/mihomo/releases/download/v1.19.21/mihomo-linux-amd64-compatible-v1.19.21.gz
          gzip -d mihomo.gz
          chmod +x mihomo

      - name: Generate domain list
        run: |
          curl -s https://raw.githubusercontent.com/lingeringsound/10007_auto/master/all | grep '^0\.0\.0\.0' | awk '{print $2}' > list.txt

      - name: Build MRS
        run: ./mihomo convert-ruleset domain text list.txt 10007.mrs

      # 👇 这里改用原生 git，彻底告别第三方 Action！不再提示！
      - name: Git Commit Push
        run: |
          git config --local user.name "GitHub Action"
          git config --local user.email "action@github.com"
          git add 10007.mrs
          git commit -m "Daily Update MRS" || exit 0
          git push https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:${{ github.ref_name }}
